import { PaketTripsInterfaces } from "../interfaces/PaketTripsInterfaces";

const paketTripsData: PaketTripsInterfaces[] = [
  {
    id: 1,
    title: "Bali Adventure",
    image: "/paket/bali.jpg",
    price: 2400000,
    rating: 4.8,
    summary: "Nikmati petualangan luar biasa di Bali dengan pantai eksotis dan budaya unik.",
    include: ["Hotel", "Makan", "Transportasi"],
    exclude: ["Tiket pesawat", "Asuransi"],
    tnc: "Tidak dapat dikembalikan setelah pembelian.",
    pax: "Max 10 orang",
    location: "Bali, Indonesia",
    riview: "2.3rb Review",
    slug: "bali-adventure", // Ditambahkan slug
  },
  {
    id: 2,
    title: "Jungle Trekking in Sumatra",
    image: "/paket/sumatra.jpg",
    price: 1300000,
    rating: 4.5,
    summary: "Jelajahi hutan Sumatera yang lebat dan temukan satwa liar yang menakjubkan.",
    include: ["Pemandu", "Makan", "Tenda"],
    exclude: ["Transportasi", "Asuransi"],
    tnc: "Pembatalan dikenakan biaya 20%.",
    pax: "Max 8 orang",
    location: "Sumatra, Indonesia",
    riview: "1.8rb Review",
    slug: "jungle-trekking-in-sumatra", // Ditambahkan slug
  },
  {
    id: 3,
    title: "Cultural Tour in Yogyakarta",
    image: "/paket/yogyakarta.jpg",
    price: 1200000,
    rating: 4.7,
    summary: "Pelajari budaya Jawa yang kaya dengan kunjungan ke candi dan keraton.",
    include: ["Hotel", "Makan", "Transportasi"],
    exclude: ["Tiket pesawat", "Asuransi"],
    tnc: "Tidak dapat dikembalikan setelah pembelian.",
    pax: "Max 12 orang",
    location: "Yogyakarta, Indonesia",
    riview: "2.1rb Review",
    slug: "cultural-tour-in-yogyakarta", // Ditambahkan slug
  },
  {
    id: 4,
    title: "Diving in Raja Ampat",
    image: "/paket/rajaampat.jpg",
    price: 1500000,
    rating: 4.9,
    summary: "Menyelamlah di surga bawah laut Raja Ampat dengan keanekaragaman hayati yang luar biasa.",
    include: ["Penginapan", "Makan", "Peralatan menyelam"],
    exclude: ["Tiket pesawat", "Asuransi"],
    tnc: "Pembatalan dikenakan biaya 30%.",
    pax: "Max 6 orang",
    location: "Raja Ampat, Indonesia",
    riview: "3.2rb Review",
    slug: "diving-in-raja-ampat", // Ditambahkan slug
  },
  {
    id: 5,
    title: "Volcano Hiking in Java",
    image: "/paket/volcano.jpg",
    price: 1000000,
    rating: 4.6,
    summary: "Mendaki gunung berapi aktif di Jawa dan nikmati pemandangan spektakuler.",
    include: ["Pemandu", "Makan", "Transportasi"],
    exclude: ["Hotel", "Asuransi"],
    tnc: "Tidak dapat dikembalikan setelah pembelian.",
    pax: "Max 15 orang",
    location: "Jawa, Indonesia",
    riview: "1.5rb Review",
    slug: "volcano-hiking-in-java", // Ditambahkan slug
  },
  {
    id: 6,
    title: "Beach Relaxation in Lombok",
    image: "/paket/lombok.jpg",
    price: 1700000,
    rating: 4.7,
    summary: "Santai di pantai-pantai indah Lombok dengan pasir putih dan air jernih.",
    include: ["Hotel", "Makan", "Transportasi"],
    exclude: ["Tiket pesawat", "Asuransi"],
    tnc: "Pembatalan dikenakan biaya 10%.",
    pax: "Max 10 orang",
    location: "Lombok, Indonesia",
    riview: "2.0rb Review",
    slug: "beach-relaxation-in-lombok", // Ditambahkan slug
  },
  {
    id: 7,
    title: "Wildlife Safari in Kalimantan",
    image: "/paket/kalimantan.jpg",
    price: 2500000,
    rating: 4.8,
    summary: "Temukan satwa liar unik seperti orangutan di hutan Kalimantan.",
    include: ["Penginapan", "Makan", "Pemandu"],
    exclude: ["Transportasi", "Asuransi"],
    tnc: "Tidak dapat dikembalikan setelah pembelian.",
    pax: "Max 8 orang",
    location: "Kalimantan, Indonesia",
    riview: "2.5rb Review",
    slug: "wildlife-safari-in-kalimantan", // Ditambahkan slug
  },
  {
    id: 8,
    title: "Historical Tour in Jakarta",
    image: "/paket/jakarta.jpg",
    price: 1500000,
    rating: 4.4,
    summary: "Jelajahi sejarah Jakarta dengan kunjungan ke museum dan monumen bersejarah.",
    include: ["Transportasi", "Makan", "Pemandu"],
    exclude: ["Hotel", "Asuransi"],
    tnc: "Pembatalan dikenakan biaya 15%.",
    pax: "Max 20 orang",
    location: "Jakarta, Indonesia",
    riview: "1.9rb Review",
    slug: "historical-tour-in-jakarta", // Ditambahkan slug
  },
  {
    id: 9,
    title: "Island Hopping in Flores",
    image: "/paket/flores.jpg",
    price: 1700000,
    rating: 4.9,
    summary: "Jelajahi pulau-pulau indah di Flores dengan pemandangan alam yang menakjubkan.",
    include: ["Penginapan", "Makan", "Transportasi"],
    exclude: ["Tiket pesawat", "Asuransi"],
    tnc: "Tidak dapat dikembalikan setelah pembelian.",
    pax: "Max 10 orang",
    location: "Flores, Indonesia",
    riview: "2.7rb Review",
    slug: "island-hopping-in-flores", // Ditambahkan slug
  },
];

export default paketTripsData;