import { PopularItemsInterface } from "../interfaces/PopularItemsInterface";

const PopularItem: PopularItemsInterface[] = [
  // Wisata
  {
    title: "Trans Snow World Bekasi",
    location: "Bekasi Timur, Bekasi",
    rating: "4.3/5 (2.3rb Review)",
    price: "Rp 50.000",
    oldPrice: "Rp 150.000",
    image: "/product/snow.jpg",
    type: "wisata",
    slug: "trans-snow-world-bekasi",
    fasilitas: ["Area bermain salju", "Tiket masuk", "Parkir gratis"],
  },
  {
    title: "Enchanting Valley Bogor",
    location: "Cisarua, Bogor",
    rating: "5/5 (24 Review)",
    price: "Rp 160.000",
    image: "/product/valley.jpg",
    type: "wisata",
    slug: "enchanting-valley-bogor",
    fasilitas: ["Pemandangan alam", "Area foto", "Tiket masuk"],
  },
  {
    title: "Wahoo Waterworld Bandung",
    location: "Padalarang, Bandung",
    rating: "4.6/5 (1.5rb Review)",
    price: "Rp 80.000",
    image: "/product/worderbandung.jpg",
    type: "wisata",
    slug: "wahoo-waterworld-bandung",
    fasilitas: ["Kolam renang", "Wahana air", "Area makan"],
  },
  {
    title: "Faunaland Ancol",
    location: "Jakarta Utara, Jakarta",
    rating: "4.7/5 (608 Review)",
    price: "Rp 77.000",
    oldPrice: "Rp 80.000",
    image: "/product/faunalandancol.jpg",
    type: "wisata",
    slug: "faunaland-ancol",
    fasilitas: ["Kebun binatang", "Wahana bermain", "Tiket masuk"],
  },
  {
    title: "Tiket Go! Wet Waterpark Bekasi",
    location: "Tambun, Bekasi",
    rating: "4.6/5 (764 Review)",
    price: "Rp 65.000",
    oldPrice: "Rp 100.000",
    image: "/product/wetwaterpark.jpg",
    type: "wisata",
    slug: "go-wet-waterpark-bekasi",
    fasilitas: ["Wahana air", "Kolam renang", "Area makan"],
  },
  {
    title: "Kebun Raya Bogor",
    location: "Bogor, Jawa Barat",
    rating: "4.5/5 (1.2rb Review)",
    price: "Rp 25.000",
    image: "/product/kebunraya.jpg",
    type: "wisata",
    slug: "kebun-raya-bogor",
    fasilitas: ["Taman botani", "Area piknik", "Tiket masuk"],
  },
  {
    title: "Taman Safari Indonesia",
    location: "Cisarua, Bogor",
    rating: "4.7/5 (1.8rb Review)",
    price: "Rp 200.000",
    image: "/product/taman.jpg",
    type: "wisata",
    slug: "taman-safari-indonesia",
    fasilitas: ["Safari hewan", "Wahana bermain", "Tiket masuk"],
  },
  {
    title: "Pantai Pandawa Bali",
    location: "Bali",
    rating: "4.8/5 (2.1rb Review)",
    price: "Rp 30.000",
    image: "/product/pandawa.jpg",
    type: "wisata",
    slug: "pantai-pandawa-bali",
    fasilitas: ["Pantai berpasir putih", "Area foto", "Tiket masuk"],
  },
  {
    title: "Candi Borobudur",
    location: "Magelang, Jawa Tengah",
    rating: "4.9/5 (2.5rb Review)",
    price: "Rp 50.000",
    image: "/product/borubudur.jpg",
    type: "wisata",
    slug: "candi-borobudur",
    fasilitas: ["Wisata sejarah", "Area foto", "Tiket masuk"],
  },
  {
    title: "Gunung Bromo",
    location: "Probolinggo, Jawa Timur",
    rating: "4.8/5 (1.9rb Review)",
    price: "Rp 100.000",
    image: "/product/bromo.jpg",
    type: "wisata",
    slug: "gunung-bromo",
    fasilitas: ["Pemandangan gunung", "Jeep tour", "Tiket masuk"],
  },
  // Hotel
  {
    title: "Hotel Mulia Senayan",
    location: "Jakarta Pusat, Jakarta",
    rating: "4.8/5 (1.2rb Review)",
    price: "Rp 2.500.000",
    image: "/product/muliasenayan.jpg",
    type: "hotel",
    slug: "hotel-mulia-senayan",
    fasilitas: ["Kolam renang", "WiFi gratis", "Sarapan"],
  },
  {
    title: "Aryaduta Bandung",
    location: "Bandung, Jawa Barat",
    rating: "4.5/5 (876 Review)",
    price: "Rp 1.200.000",
    image: "/product/aryaduta.jpg",
    type: "hotel",
    slug: "aryaduta-bandung",
    fasilitas: ["Kolam renang", "Restoran", "WiFi gratis"],
  },
  {
    title: "Grand Hyatt Jakarta",
    location: "Jakarta Pusat, Jakarta",
    rating: "4.9/5 (2.3rb Review)",
    price: "Rp 3.500.000",
    image: "/product/hyatt.jpg",
    type: "hotel",
    slug: "grand-hyatt-jakarta",
    fasilitas: ["Spa", "Kolam renang", "Sarapan"],
  },
  {
    title: "The Trans Luxury Hotel",
    location: "Bandung, Jawa Barat",
    rating: "4.8/5 (1.5rb Review)",
    price: "Rp 2.800.000",
    image: "/product/luxury.jpg",
    type: "hotel",
    slug: "the-trans-luxury-hotel",
    fasilitas: ["Kolam renang", "Restoran", "Spa"],
  },
  {
    title: "Sheraton Surabaya Hotel & Towers",
    location: "Surabaya, Jawa Timur",
    rating: "4.7/5 (1.2rb Review)",
    price: "Rp 2.200.000",
    image: "/product/sheraton.jpg",
    type: "hotel",
    slug: "sheraton-surabaya-hotel-towers",
    fasilitas: ["Kolam renang", "WiFi gratis", "Sarapan"],
  },
  {
    title: "Four Seasons Jakarta",
    location: "Jakarta Selatan, Jakarta",
    rating: "4.9/5 (1.8rb Review)",
    price: "Rp 4.000.000",
    image: "/product/sheraton.jpg",
    type: "hotel",
    slug: "four-seasons-jakarta",
    fasilitas: ["Spa", "Kolam renang", "Restoran"],
  },
  {
    title: "The Ritz-Carlton Bali",
    location: "Bali",
    rating: "4.9/5 (2.1rb Review)",
    price: "Rp 5.000.000",
    image: "/product/luxury.jpg",
    type: "hotel",
    slug: "the-ritz-carlton-bali",
    fasilitas: ["Pantai pribadi", "Spa", "Kolam renang"],
  },
  {
    title: "InterContinental Bali Resort",
    location: "Bali",
    rating: "4.8/5 (1.7rb Review)",
    price: "Rp 4.500.000",
    image: "/product/hyatt.jpg",
    type: "hotel",
    slug: "intercontinental-bali-resort",
    fasilitas: ["Kolam renang", "Restoran", "Spa"],
  },
  {
    title: "JW Marriott Hotel Jakarta",
    location: "Jakarta Selatan, Jakarta",
    rating: "4.7/5 (1.4rb Review)",
    price: "Rp 3.200.000",
    image: "/product/aryaduta.jpg",
    type: "hotel",
    slug: "jw-marriott-hotel-jakarta",
    fasilitas: ["Kolam renang", "WiFi gratis", "Sarapan"],
  },
  {
    title: "Hilton Bandung",
    location: "Bandung, Jawa Barat",
    rating: "4.6/5 (1.1rb Review)",
    price: "Rp 1.800.000",
    image: "/product/muliasenayan.jpg",
    type: "hotel",
    slug: "hilton-bandung",
    fasilitas: ["Kolam renang", "Restoran", "WiFi gratis"],
  },
  // Pesawat
  {
    title: "Penerbangan Jakarta - Bali",
    location: "Garuda Indonesia",
    rating: "4.7/5 (5.4rb Review)",
    price: "Rp 1.500.000",
    image: "/product/pesawat.jpg",
    type: "pesawat",
    slug: "penerbangan-jakarta-bali",
    fasilitas: ["Bagasi 20kg", "Makanan", "Hiburan dalam penerbangan"],
  },
  {
    title: "Penerbangan Surabaya - Medan",
    location: "Lion Air",
    rating: "4.2/5 (3.1rb Review)",
    price: "Rp 1.100.000",
    image: "/product/pesawat.jpg",
    type: "pesawat",
    slug: "penerbangan-surabaya-medan",
    fasilitas: ["Bagasi 15kg", "Makanan", "Hiburan dalam penerbangan"],
  },
  {
    title: "Penerbangan Bandung - Makassar",
    location: "Batik Air",
    rating: "4.6/5 (2.5rb Review)",
    price: "Rp 1.300.000",
    image: "/product/pesawat.jpg",
    type: "pesawat",
    slug: "penerbangan-bandung-makassar",
    fasilitas: ["Bagasi 20kg", "Makanan", "Hiburan dalam penerbangan"],
  },
  {
    title: "Penerbangan Yogyakarta - Lombok",
    location: "Citilink",
    rating: "4.4/5 (1.9rb Review)",
    price: "Rp 950.000",
    image: "/product/pesawat.jpg",
    type: "pesawat",
    slug: "penerbangan-yogyakarta-lombok",
    fasilitas: ["Bagasi 15kg", "Makanan", "Hiburan dalam penerbangan"],
  },
  {
    title: "Penerbangan Medan - Balikpapan",
    location: "Sriwijaya Air",
    rating: "4.3/5 (1.2rb Review)",
    price: "Rp 1.400.000",
    image: "/product/pesawat.jpg",
    type: "pesawat",
    slug: "penerbangan-medan-balikpapan",
    fasilitas: ["Bagasi 20kg", "Makanan", "Hiburan dalam penerbangan"],
  },
  {
    title: "Penerbangan Jakarta - Singapore",
    location: "Singapore Airlines",
    rating: "4.8/5 (3.2rb Review)",
    price: "Rp 2.000.000",
    image: "/product/pesawat.jpg",
    type: "pesawat",
    slug: "penerbangan-jakarta-singapore",
    fasilitas: ["Bagasi 30kg", "Makanan", "Hiburan dalam penerbangan"],
  },
  {
    title: "Penerbangan Denpasar - Kuala Lumpur",
    location: "AirAsia",
    rating: "4.5/5 (2.1rb Review)",
    price: "Rp 1.800.000",
    image: "/product/pesawat.jpg",
    type: "pesawat",
    slug: "penerbangan-denpasar-kuala-lumpur",
    fasilitas: ["Bagasi 20kg", "Makanan", "Hiburan dalam penerbangan"],
  },
  {
    title: "Penerbangan Surabaya - Hong Kong",
    location: "Cathay Pacific",
    rating: "4.7/5 (1.9rb Review)",
    price: "Rp 2.500.000",
    image: "/product/pesawat.jpg",
    type: "pesawat",
    slug: "penerbangan-surabaya-hong-kong",
    fasilitas: ["Bagasi 30kg", "Makanan", "Hiburan dalam penerbangan"],
  },
  {
    title: "Penerbangan Jakarta - Tokyo",
    location: "Japan Airlines",
    rating: "4.9/5 (2.3rb Review)",
    price: "Rp 3.000.000",
    image: "/product/pesawat.jpg",
    type: "pesawat",
    slug: "penerbangan-jakarta-tokyo",
    fasilitas: ["Bagasi 30kg", "Makanan", "Hiburan dalam penerbangan"],
  },
  {
    title: "Penerbangan Medan - Penang",
    location: "Malaysia Airlines",
    rating: "4.4/5 (1.5rb Review)",
    price: "Rp 1.600.000",
    image: "/product/pesawat.jpg",
    type: "pesawat",
    slug: "penerbangan-medan-penang",
    fasilitas: ["Bagasi 20kg", "Makanan", "Hiburan dalam penerbangan"],
  },
  // Kereta
  {
    title: "Kereta Argo Parahyangan",
    location: "Jakarta - Bandung",
    rating: "4.6/5 (2.8rb Review)",
    price: "Rp 250.000",
    image: "/product/kereta.jpg",
    type: "kereta",
    slug: "kereta-argo-parahyangan",
    fasilitas: ["AC", "Makanan", "WiFi"],
  },
  {
    title: "Kereta Taksaka",
    location: "Jakarta - Yogyakarta",
    rating: "4.8/5 (1.9rb Review)",
    price: "Rp 350.000",
    image: "/product/kereta.jpg",
    type: "kereta",
    slug: "kereta-taksaka",
    fasilitas: ["AC", "Makanan", "WiFi"],
  },
  {
    title: "Kereta Gajayana",
    location: "Malang - Jakarta",
    rating: "4.7/5 (1.5rb Review)",
    price: "Rp 400.000",
    image: "/product/kereta.jpg",
    type: "kereta",
    slug: "kereta-gajayana",
    fasilitas: ["AC", "Makanan", "WiFi"],
  },
  {
    title: "Kereta Bima",
    location: "Jakarta - Surabaya",
    rating: "4.6/5 (1.8rb Review)",
    price: "Rp 380.000",
    image: "/product/kereta.jpg",
    type: "kereta",
    slug: "kereta-bima",
    fasilitas: ["AC", "Makanan", "WiFi"],
  },
  {
    title: "Kereta Argo Wilis",
    location: "Bandung - Surabaya",
    rating: "4.5/5 (1.3rb Review)",
    price: "Rp 420.000",
    image: "/product/kereta.jpg",
    type: "kereta",
    slug: "kereta-argo-wilis",
    fasilitas: ["AC", "Makanan", "WiFi"],
  },
  {
    title: "Kereta Sembrani",
    location: "Jakarta - Surabaya",
    rating: "4.7/5 (1.6rb Review)",
    price: "Rp 450.000",
    image: "/product/kereta.jpg",
    type: "kereta",
    slug: "kereta-sembrani",
    fasilitas: ["AC", "Makanan", "WiFi"],
  },
  {
    title: "Kereta Mutiara Selatan",
    location: "Bandung - Surabaya",
    rating: "4.6/5 (1.4rb Review)",
    price: "Rp 400.000",
    image: "/product/kereta.jpg",
    type: "kereta",
    slug: "kereta-mutiara-selatan",
    fasilitas: ["AC", "Makanan", "WiFi"],
  },
  {
    title: "Kereta Lodaya",
    location: "Bandung - Solo",
    rating: "4.5/5 (1.2rb Review)",
    price: "Rp 300.000",
    image: "/product/kereta.jpg",
    type: "kereta",
    slug: "kereta-lodaya",
    fasilitas: ["AC", "Makanan", "WiFi"],
  },
  {
    title: "Kereta Fajar Utama",
    location: "Jakarta - Yogyakarta",
    rating: "4.6/5 (1.3rb Review)",
    price: "Rp 320.000",
    image: "/product/kereta.jpg",
    type: "kereta",
    slug: "kereta-fajar-utama",
    fasilitas: ["AC", "Makanan", "WiFi"],
  },
  // Event
  {
    title: "Java Jazz Festival 2023",
    location: "Jakarta International Expo, Jakarta",
    rating: "4.8/5 (5.2rb Review)",
    price: "Rp 1.000.000",
    image: "/product/events.jpg",
    type: "event",
    slug: "java-jazz-festival-2023",
    fasilitas: ["Konser musik", "Area makanan", "Merchandise"],
  },
  {
    title: "DWP Adventure 2023",
    location: "Dufan, Jakarta",
    rating: "4.7/5 (4.8rb Review)",
    price: "Rp 500.000",
    image: "/product/events.jpg",
    type: "event",
    slug: "dwp-adventure-2023",
    fasilitas: ["Wahana bermain", "Konser musik", "Area makanan"],
  },
  {
    title: "We The Fest 2023",
    location: "GBK, Jakarta",
    rating: "4.9/5 (6.1rb Review)",
    price: "Rp 1.500.000",
    image: "/product/events.jpg",
    type: "event",
    slug: "we-the-fest-2023",
    fasilitas: ["Konser musik", "Area makanan", "Merchandise"],
  },
  {
    title: "Soundrenaline 2023",
    location: "Bali",
    rating: "4.8/5 (5.5rb Review)",
    price: "Rp 1.200.000",
    image: "/product/events.jpg",
    type: "event",
    slug: "soundrenaline-2023",
    fasilitas: ["Konser musik", "Area makanan", "Merchandise"],
  },
  {
    title: "Jakarta Fair 2023",
    location: "Jakarta International Expo, Jakarta",
    rating: "4.6/5 (4.2rb Review)",
    price: "Rp 100.000",
    image: "/product/events.jpg",
    type: "event",
    slug: "jakarta-fair-2023",
    fasilitas: ["Pameran", "Area makanan", "Diskon produk"],
  },
  {
    title: "Bali Arts Festival 2023",
    location: "Bali",
    rating: "4.7/5 (3.9rb Review)",
    price: "Rp 200.000",
    image: "/product/events.jpg",
    type: "event",
    slug: "bali-arts-festival-2023",
    fasilitas: ["Pertunjukan seni", "Area makanan", "Merchandise"],
  },
  {
    title: "Synchronize Fest 2023",
    location: "Jakarta",
    rating: "4.8/5 (4.5rb Review)",
    price: "Rp 1.300.000",
    image: "/product/events.jpg",
    type: "event",
    slug: "synchronize-fest-2023",
    fasilitas: ["Konser musik", "Area makanan", "Merchandise"],
  },
  {
    title: "Jogja Food Festival 2023",
    location: "Yogyakarta",
    rating: "4.6/5 (3.2rb Review)",
    price: "Rp 150.000",
    image: "/product/events.jpg",
    type: "event",
    slug: "jogja-food-festival-2023",
    fasilitas: ["Makanan khas", "Area hiburan", "Diskon produk"],
  },
  {
    title: "Bandung Music Festival 2023",
    location: "Bandung",
    rating: "4.7/5 (3.5rb Review)",
    price: "Rp 800.000",
    image: "/product/events.jpg",
    type: "event",
    slug: "bandung-music-festival-2023",
    fasilitas: ["Konser musik", "Area makanan", "Merchandise"],
  },
  {
    title: "Surabaya Fashion Week 2023",
    location: "Surabaya",
    rating: "4.5/5 (2.8rb Review)",
    price: "Rp 300.000",
    image: "/product/events.jpg",
    type: "event",
    slug: "surabaya-fashion-week-2023",
    fasilitas: ["Pameran fashion", "Area makanan", "Diskon produk"],
  },
  // Kapal Ferry
  {
    title: "Ferry Jakarta - Batam",
    location: "Pelni",
    rating: "4.5/5 (1.2rb Review)",
    price: "Rp 500.000",
    image: "/product/kapalfeery.jpg",
    type: "kapal ferry",
    slug: "ferry-jakarta-batam",
    fasilitas: ["Kabin tidur", "Makanan", "Hiburan"],
  },
  {
    title: "Ferry Surabaya - Balikpapan",
    location: "Pelni",
    rating: "4.4/5 (1.1rb Review)",
    price: "Rp 600.000",
    image: "/product/kapalfeery.jpg",
    type: "kapal ferry",
    slug: "ferry-surabaya-balikpapan",
    fasilitas: ["Kabin tidur", "Makanan", "Hiburan"],
  },
  {
    title: "Ferry Jakarta - Lampung",
    location: "Pelni",
    rating: "4.3/5 (900 Review)",
    price: "Rp 400.000",
    image: "/product/kapalfeery.jpg",
    type: "kapal ferry",
    slug: "ferry-jakarta-lampung",
    fasilitas: ["Kabin tidur", "Makanan", "Hiburan"],
  },
  {
    title: "Ferry Semarang - Kumai",
    location: "Pelni",
    rating: "4.2/5 (800 Review)",
    price: "Rp 450.000",
    image: "/product/kapalfeery.jpg",
    type: "kapal ferry",
    slug: "ferry-semarang-kumai",
    fasilitas: ["Kabin tidur", "Makanan", "Hiburan"],
  },
  {
    title: "Ferry Makassar - Parepare",
    location: "Pelni",
    rating: "4.1/5 (700 Review)",
    price: "Rp 300.000",
    image: "/product/kapalfeery.jpg",
    type: "kapal ferry",
    slug: "ferry-makassar-parepare",
    fasilitas: ["Kabin tidur", "Makanan", "Hiburan"],
  },
  {
    title: "Ferry Bali - Lombok",
    location: "Pelni",
    rating: "4.6/5 (1.3rb Review)",
    price: "Rp 350.000",
    image: "/product/kapalfeery.jpg",
    type: "kapal ferry",
    slug: "ferry-bali-lombok",
    fasilitas: ["Kabin tidur", "Makanan", "Hiburan"],
  },
  {
    title: "Ferry Batam - Bintan",
    location: "Pelni",
    rating: "4.5/5 (1.1rb Review)",
    price: "Rp 200.000",
    image: "/product/kapalfeery.jpg",
    type: "kapal ferry",
    slug: "ferry-batam-bintan",
    fasilitas: ["Kabin tidur", "Makanan", "Hiburan"],
  },
  {
    title: "Ferry Jakarta - Karimun Jawa",
    location: "Pelni",
    rating: "4.4/5 (1.0rb Review)",
    price: "Rp 550.000",
    image: "/product/kapalfeery.jpg",
    type: "kapal ferry",
    slug: "ferry-jakarta-karimun-jawa",
    fasilitas: ["Kabin tidur", "Makanan", "Hiburan"],
  },
  {
    title: "Ferry Surabaya - Banjarmasin",
    location: "Pelni",
    rating: "4.3/5 (950 Review)",
    price: "Rp 500.000",
    image: "/product/kapalfeery.jpg",
    type: "kapal ferry",
    slug: "ferry-surabaya-banjarmasin",
    fasilitas: ["Kabin tidur", "Makanan", "Hiburan"],
  },
  {
    title: "Ferry Makassar - Balikpapan",
    location: "Pelni",
    rating: "4.2/5 (850 Review)",
    price: "Rp 600.000",
    image: "/product/kapalfeery.jpg",
    type: "kapal ferry",
    slug: "ferry-makassar-balikpapan",
    fasilitas: ["Kabin tidur", "Makanan", "Hiburan"],
  },
];

export default PopularItem;